# Generated by Django 3.1.7 on 2022-08-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Role_name', models.CharField(max_length=20, verbose_name='Role Name')),
                ('Role_create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('Role_modify_at', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
            ],
            options={
                'verbose_name': 'Role Management System',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_UPI', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='UPI')),
                ('User_password', models.CharField(max_length=20, verbose_name='Password')),
                ('User_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('User_first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('User_last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('User_create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('User_modify_at', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
            ],
            options={
                'verbose_name': 'User Management System',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Users_roles',
            fields=[
                ('Users_roles_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('User_role_Role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mark_App.role')),
                ('Users_roles_UPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mark_App.user')),
            ],
        ),
    ]
