# Generated by Django 3.1.7 on 2022-08-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester_summer', models.BooleanField(default=False, verbose_name='Summer Semester')),
                ('Semester_one', models.BooleanField(default=False)),
                ('Semester_two', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('Student_middle_name', models.CharField(max_length=30, null=True, verbose_name='Middle Name')),
                ('Student_last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('Student_UPI', models.CharField(max_length=10, verbose_name='UPI')),
                ('Student_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Student Management System',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=30)),
                ('Course_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkingPlatform.semester')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
