# Generated by Django 3.1.7 on 2022-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkingPlatform', '0002_auto_20220813_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_semester',
            field=models.IntegerField(choices=[(0, 'Summer Semester'), (1, 'Semester One'), (2, 'Semester Two'), (-1, 'null')], default=-1),
        ),
    ]
