"""add gpa

Revision ID: 0217e231842a
Revises: 1fd14b6620af
Create Date: 2022-10-09 02:08:02.852433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0217e231842a'
down_revision = '1fd14b6620af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_profile', sa.Column('gpa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_profile', 'gpa')
    # ### end Alembic commands ###
