"""'inviteuser'

Revision ID: 1fd14b6620af
Revises: 
Create Date: 2022-10-04 04:59:35.953061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd14b6620af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_user_saved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('userID', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('saver_user_id', sa.String(length=255), nullable=True),
    sa.Column('savedDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['saver_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_user_saved_groups',
    sa.Column('inviteUserID', sa.Integer(), nullable=False),
    sa.Column('groupID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groupID'], ['groups.groupID'], ),
    sa.ForeignKeyConstraint(['inviteUserID'], ['invite_user_saved.id'], ),
    sa.PrimaryKeyConstraint('inviteUserID', 'groupID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_user_saved_groups')
    op.drop_table('invite_user_saved')
    # ### end Alembic commands ###
