"""empty message

Revision ID: 4d2eab68e4ed
Revises: 4e7ec7fdfb95
Create Date: 2022-10-10 19:55:28.532271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2eab68e4ed'
down_revision = '4e7ec7fdfb95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
