"""add status to application

Revision ID: 7ac76a2c0994
Revises: 
Create Date: 2022-09-27 01:00:02.681197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac76a2c0994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('status', sa.Enum('Unsubmit', 'Pending', 'Success', 'Fail', name='applicationstatus')))
    op.add_column('application', sa.Column('resultMesg', sa.String(length=1024), nullable=True))
    op.drop_column('application', 'isCompleted')
    op.add_column('course_application', sa.Column('preference', sa.Integer(), nullable=True))
    op.drop_column('course_application', 'status')
    op.drop_column('course_application', 'resultMesg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_application', sa.Column('resultMesg', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('course_application', sa.Column('status', sa.VARCHAR(length=7), nullable=True))
    op.drop_column('course_application', 'preference')
    op.add_column('application', sa.Column('isCompleted', sa.BOOLEAN(), nullable=True))
    op.drop_column('application', 'resultMesg')
    op.drop_column('application', 'status')
    # ### end Alembic commands ###
