"""add courseCoordinatorEndorsed

Revision ID: 87918972f4a5
Revises: d2d89c232805
Create Date: 2022-10-09 21:03:22.598199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87918972f4a5'
down_revision = 'd2d89c232805'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_application', sa.Column('courseCoordinatorEndorsed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_application', 'courseCoordinatorEndorsed')
    # ### end Alembic commands ###
