"""init

Revision ID: 94ceddea0611
Revises: 
Create Date: 2022-10-12 17:46:39.116037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ceddea0611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('deadLine')

    with op.batch_alter_table('course_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('courseCoordinatorEndorsed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('course_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ApplicationID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimatedHours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('isPublished', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_course_user_ApplicationID_application'), 'application', ['ApplicationID'], ['ApplicationID'])

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_groups_groupName'), ['groupName'])

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_permission_name'), ['name'])

    with op.batch_alter_table('role_in_course', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_role_in_course_Name'), ['Name'])

    with op.batch_alter_table('saved_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpa', sa.Float(), nullable=True))

    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defaultMarkerDeadLine', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('defaultTutorDeadLine', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_term_termName'), ['termName'])
        batch_op.drop_column('defaultDeadLine')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defaultDeadLine', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_term_termName'), type_='unique')
        batch_op.drop_column('defaultTutorDeadLine')
        batch_op.drop_column('defaultMarkerDeadLine')

    with op.batch_alter_table('saved_profile', schema=None) as batch_op:
        batch_op.drop_column('gpa')

    with op.batch_alter_table('role_in_course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_role_in_course_Name'), type_='unique')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_permission_name'), type_='unique')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_groups_groupName'), type_='unique')

    with op.batch_alter_table('course_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_course_user_ApplicationID_application'), type_='foreignkey')
        batch_op.drop_column('isPublished')
        batch_op.drop_column('estimatedHours')
        batch_op.drop_column('ApplicationID')

    with op.batch_alter_table('course_application', schema=None) as batch_op:
        batch_op.drop_column('courseCoordinatorEndorsed')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadLine', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
