"""add tutor marker deadline

Revision ID: a4229c5bafba
Revises: d56ab185856b
Create Date: 2022-10-10 16:30:38.831712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4229c5bafba'
down_revision = 'd56ab185856b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('markerDeadLine', sa.DateTime(), nullable=True))
    op.add_column('course', sa.Column('tutorDeadLine', sa.DateTime(), nullable=True))
    op.drop_column('course', 'deadLine')
    op.add_column('term', sa.Column('defaultMarkerDeadLine', sa.DateTime(), nullable=True))
    op.add_column('term', sa.Column('defaultTutorDeadLine', sa.DateTime(), nullable=True))
    op.drop_column('term', 'defaultDeadLine')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('term', sa.Column('defaultDeadLine', sa.DATETIME(), nullable=True))
    op.drop_column('term', 'defaultTutorDeadLine')
    op.drop_column('term', 'defaultMarkerDeadLine')
    op.add_column('course', sa.Column('deadLine', sa.DATETIME(), nullable=True))
    op.drop_column('course', 'tutorDeadLine')
    op.drop_column('course', 'markerDeadLine')
    # ### end Alembic commands ###
