"""add setting

Revision ID: b008455a44af
Revises: 0217e231842a
Create Date: 2022-10-09 14:32:37.114947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b008455a44af'
down_revision = '0217e231842a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('settingID', sa.Integer(), nullable=False),
    sa.Column('uniqueEmail', sa.Boolean(), nullable=True),
    sa.Column('allowRegister', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('settingID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
