"""add row to application

Revision ID: d2d89c232805
Revises: b008455a44af
Create Date: 2022-10-09 15:33:29.025676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d89c232805'
down_revision = 'b008455a44af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('isResultPublished', sa.Boolean(), nullable=True))
    op.add_column('application', sa.Column('type', sa.Enum('Marker', 'Tutor', name='applicationtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'type')
    op.drop_column('application', 'isResultPublished')
    # ### end Alembic commands ###
