"""add estimatedHours to courseuser

Revision ID: d56ab185856b
Revises: 87918972f4a5
Create Date: 2022-10-10 04:48:43.993919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56ab185856b'
down_revision = '87918972f4a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_user', sa.Column('estimatedHours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_user', 'estimatedHours')
    # ### end Alembic commands ###
