# Generated by Django 3.1.7 on 2022-08-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkingPlatform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_middle_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
