# Generated by Django 3.1.7 on 2022-08-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkingPlatform', '0003_auto_20220813_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_code',
            field=models.CharField(default=2, max_length=30, unique=True, verbose_name='Course Code'),
            preserve_default=False,
        ),
    ]
